### ISSUE TITLE
Usage with ts-jest

### ISSUE THREAD

**Issue by DamianPereira** [kimamula/ts-transformer-keys#42]
As far as I understood, ts-jest supports typescript transformers with the [astTransformers](https://kulshekhar.github.io/ts-jest/user/config/astTransformers) option. I tried to make it work like this in my jest.config.js:
```javascript
  globals: {
    'ts-jest': {
      astTransformers: {
        before: ['ts-transformer-keys/transformer'],
      },
    },
  },
```
This did not work and results in the error `TypeError: ts_transformer_keys_1.keys is not a function`, which happens when the transform is not being applied. Any ideas?

**Comment by DamianPereira** [comment]
I managed to do it, I had to create a file like this:
`// ts-jest-keys-trasnformer.js
const keysTransformer = require('ts-transformer-keys/transformer').default;
const name = 'my-key-transformer';
const version = 1;
const factory = (cs) => (ctx) => keysTransformer(cs.tsCompiler.program)(ctx);
module.exports = { name, version, factory };`

And add it in jest.config.js like this:
`  globals: {
        'ts-jest': {
          // relative path to the ts-jest-keys-transformer.js file
          astTransformers: ['src/react/ts-jest-keys-transformer.js'],
        },
      },`

I'll create a PR adding an example and documentation

**Comment by EdNutting** [comment]
This was brilliant - thank you! Never would've figured out how to get this working without your solution.

**Comment by DamianPereira** [comment]
Glad I could help :)

**Comment by PyDario** [comment]
Unfortunately, this didn't work for me. program is undefined in this test
```
 ● Test suite failed to run

    TypeError: Cannot read property 'program' of undefined

      2 | const name = 'my-key-transformer';
      3 | const version = 1;
    > 4 | const factory = cs => ctx => keysTransformer(cs.tsCompiler.program)(ctx);
        |                                                            ^
      5 | module.exports = { name, version, factory };
      6 |

      at ts-jest-keys-transformer.js:4:60
      at node_modules/typescript/lib/typescript.js:96726:37
      at node_modules/typescript/lib/typescript.js:96819:78
          at Array.map (<anonymous>)
      at Object.transformNodes (node_modules/typescript/lib/typescript.js:96819:52)
      at emitJsFileOrBundle (node_modules/typescript/lib/typescript.js:97443:32)
      at emitSourceFileOrBundle (node_modules/typescript/lib/typescript.js:97395:13)
      at forEachEmittedFile (node_modules/typescript/lib/typescript.js:97147:34)
      at Object.emitFiles (node_modules/typescript/lib/typescript.js:97376:9)
      at emitWorker (node_modules/typescript/lib/typescript.js:103688:33)
```
